### ISSUE TITLE
GitHub搭建个人图床

### ISSUE THREAD

**Issue by BboyZJ** [13718004742/images#2]

**Comment by 13718004742** [comment]
<img width="167" alt="截屏2020-07-19上午11 38 52" src="https://user-images.githubusercontent.com/25925248/87866468-afdcc980-c9b4-11ea-8c96-c1881be9f78c.png">

**Comment by 13718004742** [comment]
<img width="917" alt="截屏2020-07-19上午11 40 29" src="https://user-images.githubusercontent.com/25925248/87866472-bc612200-c9b4-11ea-8ad8-000200d897fb.png">
