### ISSUE TITLE
Github搭建个人图床

### ISSUE THREAD

**Issue by BboyZJ** [13718004742/images#3]
<img width="917" alt="截屏2020-07-19上午11 40 29" src="https://user-images.githubusercontent.com/25925248/87866493-077b3500-c9b5-11ea-9180-4aa489b0a157.png">

**Comment by 13718004742** [comment]
<img width="167" alt="截屏2020-07-19上午11 38 52" src="https://user-images.githubusercontent.com/25925248/87866501-2083e600-c9b5-11ea-8c52-c86b08ee2430.png">

**Comment by BboyZJ** [comment]
<img width="167" alt="截屏2020-07-19上午11 38 52" src="https://user-images.githubusercontent.com/25925248/87866516-4c06d080-c9b5-11ea-871f-fdecbac33e70.png">
