### ISSUE TITLE
iOS 图像显示原理探究

### ISSUE THREAD

**Issue by BboyZJ** [13718004742/images#6]
<img width="653" alt="截屏2020-07-20下午2 50 39" src="https://user-images.githubusercontent.com/25925248/87908686-7336ce00-ca99-11ea-9ff7-e97601702851.png">

**Comment by BboyZJ** [comment]
<img width="664" alt="截屏2020-07-20下午3 25 48" src="https://user-images.githubusercontent.com/25925248/87910892-58665880-ca9d-11ea-829a-9f64e920efeb.png">

**Comment by 13718004742** [comment]
<img width="664" alt="截屏2020-07-20下午3 25 48" src="https://user-images.githubusercontent.com/25925248/87911743-b21b5280-ca9e-11ea-90be-5338d33d6481.png">

**Comment by BboyZJ** [comment]
<img width="719" alt="截屏2020-07-20下午4 54 13" src="https://user-images.githubusercontent.com/25925248/87918925-a5e8c280-caa9-11ea-86bd-642a027d2bb1.png">

**Comment by BboyZJ** [comment]
<img width="395" alt="截屏2020-07-20下午3 39 35" src="https://user-images.githubusercontent.com/25925248/87912176-7b920780-ca9f-11ea-8433-87b6ff4b0be1.png">

**Comment by BboyZJ** [comment]
<img width="515" alt="截屏2020-07-20下午4 00 59" src="https://user-images.githubusercontent.com/25925248/87913896-6bc7f280-caa2-11ea-9a58-46164cd5a0db.png">

**Comment by 13718004742** [comment]
<img width="691" alt="截屏2020-07-20下午4 21 42" src="https://user-images.githubusercontent.com/25925248/87915742-1c36f600-caa5-11ea-9c74-74005b0572d2.png">

**Comment by 13718004742** [comment]
<img width="679" alt="截屏2020-07-20下午4 23 02" src="https://user-images.githubusercontent.com/25925248/87915895-4ee0ee80-caa5-11ea-94d6-b9e0c6dac3ad.png">
